source 'https://rubygems.org'

gem 'berkshelf'
gem 'foodcritic'
gem 'thor-foodcritic'
gem 'chefspec'
gem 'test-kitchen'
gem 'chef-zero'

group :integration do
  gem 'kitchen-vagrant'
  gem 'cucumber'
  gem 'rspec-expectations'
  gem 'leibniz', '~> 0.2.1'
end

gem 'rubocop', require: false
gem 'strainer', require: false